<?php
return [
  'modules' => [
    'Magento_AdminAnalytics' => 1,
    'Magento_Store' => 1,
    'Magento_AdvancedPricingImportExport' => 1,
    'Magento_Directory' => 1,
    'Magento_Amqp' => 1,
    'Magento_AmqpStore' => 1,
    'Magento_Config' => 1,
    'Magento_Theme' => 1,
    'Magento_Backend' => 1,
    'Magento_Variable' => 1,
    'Magento_Search' => 1,
    'Magento_Backup' => 1,
    'Magento_Eav' => 1,
    'Magento_Customer' => 1,
    'Magento_BundleImportExport' => 1,
    'Magento_CacheInvalidate' => 1,
    'Magento_AdminNotification' => 1,
    'Magento_Indexer' => 1,
    'Magento_Cms' => 1,
    'Magento_Security' => 1,
    'Magento_Authorization' => 1,
    'Magento_GraphQl' => 1,
    'Magento_StoreGraphQl' => 1,
    'Magento_CatalogImportExport' => 1,
    'Magento_Catalog' => 1,
    'Magento_CatalogInventory' => 1,
    'Magento_Rule' => 1,
    'Magento_Payment' => 1,
    'Magento_CatalogRuleGraphQl' => 1,
    'Magento_CatalogRule' => 1,
    'Magento_CatalogUrlRewrite' => 1,
    'Magento_EavGraphQl' => 1,
    'Magento_Widget' => 1,
    'Magento_Quote' => 1,
    'Magento_SalesSequence' => 1,
    'Magento_CheckoutAgreementsGraphQl' => 1,
    'Magento_Bundle' => 1,
    'Magento_CmsGraphQl' => 1,
    'Magento_CmsUrlRewrite' => 1,
    'Magento_CmsUrlRewriteGraphQl' => 1,
    'Magento_CatalogGraphQl' => 1,
    'Magento_User' => 1,
    'Magento_Msrp' => 1,
    'Magento_Sales' => 1,
    'Magento_QuoteGraphQl' => 1,
    'Magento_Checkout' => 1,
    'Magento_Contact' => 1,
    'Magento_Cookie' => 1,
    'Magento_Cron' => 1,
    'Magento_Csp' => 1,
    'Magento_CurrencySymbol' => 1,
    'Magento_CatalogCustomerGraphQl' => 1,
    'Magento_Integration' => 1,
    'Magento_Downloadable' => 1,
    'Magento_CustomerGraphQl' => 1,
    'Magento_CustomerImportExport' => 1,
    'Magento_Deploy' => 1,
    'Magento_Developer' => 1,
    'Magento_Dhl' => 1,
    'Magento_AsynchronousOperations' => 1,
    'Magento_DirectoryGraphQl' => 1,
    'Magento_DownloadableGraphQl' => 1,
    'Magento_CustomerDownloadableGraphQl' => 1,
    'Magento_ImportExport' => 1,
    'Magento_Captcha' => 1,
    'Magento_BundleGraphQl' => 1,
    'Magento_CatalogSearch' => 1,
    'Magento_AdvancedSearch' => 1,
    'Magento_Elasticsearch' => 1,
    'Magento_Email' => 1,
    'Magento_EncryptionKey' => 1,
    'Magento_Fedex' => 1,
    'Magento_GiftMessage' => 1,
    'Magento_GiftMessageGraphQl' => 1,
    'Magento_GoogleAdwords' => 1,
    'Magento_GoogleAnalytics' => 1,
    'Magento_Ui' => 1,
    'Magento_CatalogCmsGraphQl' => 1,
    'Magento_PageCache' => 1,
    'Magento_GroupedProduct' => 1,
    'Magento_GroupedImportExport' => 1,
    'Magento_GroupedCatalogInventory' => 1,
    'Magento_GroupedProductGraphQl' => 1,
    'Magento_DownloadableImportExport' => 1,
    'Magento_ConfigurableProduct' => 1,
    'Magento_InstantPurchase' => 1,
    'Magento_Analytics' => 1,
    'Magento_LayeredNavigation' => 1,
    'Magento_LoginAsCustomer' => 1,
    'Magento_LoginAsCustomerAdminUi' => 1,
    'Magento_LoginAsCustomerApi' => 1,
    'Magento_LoginAsCustomerAssistance' => 1,
    'Magento_LoginAsCustomerFrontendUi' => 1,
    'Magento_LoginAsCustomerGraphQl' => 1,
    'Magento_LoginAsCustomerLog' => 1,
    'Magento_LoginAsCustomerPageCache' => 1,
    'Magento_LoginAsCustomerQuote' => 1,
    'Magento_LoginAsCustomerSales' => 1,
    'Magento_Marketplace' => 1,
    'Magento_MediaContent' => 1,
    'Magento_MediaContentApi' => 1,
    'Magento_MediaContentCatalog' => 1,
    'Magento_MediaContentCms' => 1,
    'Magento_MediaContentSynchronization' => 1,
    'Magento_MediaContentSynchronizationApi' => 1,
    'Magento_MediaContentSynchronizationCatalog' => 1,
    'Magento_MediaContentSynchronizationCms' => 1,
    'Magento_MediaGallery' => 1,
    'Magento_MediaGalleryApi' => 1,
    'Magento_MediaGalleryCatalog' => 1,
    'Magento_MediaGalleryCatalogIntegration' => 1,
    'Magento_MediaGalleryCatalogUi' => 1,
    'Magento_MediaGalleryCmsUi' => 1,
    'Magento_MediaGalleryIntegration' => 1,
    'Magento_MediaGalleryMetadata' => 1,
    'Magento_MediaGalleryMetadataApi' => 1,
    'Magento_MediaGalleryRenditions' => 1,
    'Magento_MediaGalleryRenditionsApi' => 1,
    'Magento_MediaGallerySynchronization' => 1,
    'Magento_MediaGallerySynchronizationApi' => 1,
    'Magento_MediaGallerySynchronizationMetadata' => 1,
    'Magento_MediaGalleryUi' => 1,
    'Magento_MediaGalleryUiApi' => 1,
    'Magento_Robots' => 1,
    'Magento_MessageQueue' => 1,
    'Magento_CatalogRuleConfigurable' => 1,
    'Magento_MsrpConfigurableProduct' => 1,
    'Magento_MsrpGroupedProduct' => 1,
    'Magento_Multishipping' => 1,
    'Magento_MysqlMq' => 1,
    'Magento_NewRelicReporting' => 1,
    'Magento_Newsletter' => 1,
    'Magento_NewsletterGraphQl' => 1,
    'Magento_OfflinePayments' => 1,
    'Magento_SalesRule' => 1,
    'Magento_GraphQlCache' => 1,
    'Magento_CardinalCommerce' => 1,
    'Magento_Vault' => 1,
    'Magento_Paypal' => 1,
    'Magento_PaypalGraphQl' => 1,
    'Magento_Persistent' => 1,
    'Magento_ProductAlert' => 1,
    'Magento_ProductVideo' => 1,
    'Magento_CheckoutAgreements' => 1,
    'Magento_QuoteAnalytics' => 1,
    'Magento_QuoteBundleOptions' => 1,
    'Magento_QuoteConfigurableOptions' => 1,
    'Magento_QuoteDownloadableLinks' => 1,
    'Magento_ConfigurableProductGraphQl' => 1,
    'Magento_RelatedProductGraphQl' => 1,
    'Magento_ReleaseNotification' => 1,
    'Magento_Sitemap' => 1,
    'Magento_Reports' => 1,
    'Magento_RequireJs' => 1,
    'Magento_Review' => 1,
    'Magento_ReviewAnalytics' => 1,
    'Magento_ReviewGraphQl' => 1,
    'Magento_MediaStorage' => 1,
    'Magento_Rss' => 1,
    'Magento_Elasticsearch6' => 1,
    'Magento_ConfigurableProductSales' => 1,
    'Magento_SalesAnalytics' => 1,
    'Magento_SalesGraphQl' => 1,
    'Magento_SalesInventory' => 1,
    'Magento_OfflineShipping' => 1,
    'Magento_ConfigurableImportExport' => 1,
    'Magento_UrlRewrite' => 1,
    'Magento_Elasticsearch7' => 1,
    'Magento_CustomerAnalytics' => 1,
    'Magento_SendFriend' => 1,
    'Magento_SendFriendGraphQl' => 1,
    'Magento_Shipping' => 1,
    'Magento_RemoteStorage' => 1,
    'Magento_AwsS3' => 1,
    'Magento_UrlRewriteGraphQl' => 1,
    'Magento_Webapi' => 1,
    'Magento_SwaggerWebapi' => 1,
    'Magento_SwaggerWebapiAsync' => 1,
    'Magento_Swatches' => 1,
    'Magento_SwatchesGraphQl' => 1,
    'Magento_SwatchesLayeredNavigation' => 1,
    'Magento_Tax' => 1,
    'Magento_TaxGraphQl' => 1,
    'Magento_TaxImportExport' => 1,
    'Magento_CompareListGraphQl' => 1,
    'Magento_ThemeGraphQl' => 1,
    'Magento_Tinymce3' => 1,
    'Magento_Translation' => 1,
    'Magento_GoogleOptimizer' => 1,
    'Magento_Ups' => 1,
    'Magento_SampleData' => 1,
    'Magento_CatalogUrlRewriteGraphQl' => 1,
    'Magento_CatalogAnalytics' => 1,
    'Magento_Usps' => 1,
    'Magento_CatalogInventoryGraphQl' => 1,
    'Magento_PaypalCaptcha' => 1,
    'Magento_VaultGraphQl' => 1,
    'Magento_Version' => 1,
    'Magento_Swagger' => 1,
    'Magento_WebapiAsync' => 1,
    'Magento_WebapiSecurity' => 1,
    'Magento_Weee' => 1,
    'Magento_WeeeGraphQl' => 1,
    'Magento_CatalogWidget' => 1,
    'Magento_Wishlist' => 1,
    'Magento_WishlistAnalytics' => 1,
    'Magento_WishlistGraphQl' => 1
  ],
  'system' => [
    'default' => [
      'admin' => [
        'usage' => [
          'enabled' => '
1
',
        ],
        'startup' => [
          'menu_item_id' => 'dashboard',
        ],
        'url' => [
          'use_custom' => '0',
          'use_custom_path' => '0',
        ],
        'security' => [
          'use_form_key' => '1',
          'admin_account_sharing' => '0',
          'password_reset_protection_type' => '1',
          'max_number_password_reset_requests' => '5',
          'min_time_between_password_reset_requests' => '10',
          'password_reset_link_expiration_period' => '2',
          'lockout_failures' => '6',
          'lockout_threshold' => '30',
          'password_lifetime' => '90',
          'password_is_forced' => '1',
          'session_lifetime' => '86000',
          'use_case_sensitive_login' => '0',
        ],
        'emails' => [
          'forgot_email_template' => 'admin_emails_forgot_email_template',
          'new_user_notification_template' => 'admin_emails_new_user_notification_template',
          'forgot_email_identity' => 'general',
          'user_notification_template' => 'admin_emails_user_notification_template',
        ],
        'captcha' => [
          'type' => 'default',
          'enable' => '0',
          'font' => 'linlibertine',
          'mode' => 'after_fail',
          'forms' => null,
          'failed_attempts_login' => '3',
          'failed_attempts_ip' => '1000',
          'timeout' => '7',
          'length' => '4-5',
          'symbols' => 'ABCDEFGHJKMnpqrstuvwxyz23456789',
          'case_sensitive' => '0',
          'shown_to_logged_in_user' => null,
          'always_for' => [
            'backend_forgotpassword' => '1',
          ],
        ],
        'dashboard' => [
          'enable_charts' => '1',
        ],
      ],
      'design' => [
        'pagination' => [
          'list_allow_all' => '1',
          'pagination_frame' => '5',
          'pagination_frame_skip' => null,
          'anchor_text_for_previous' => null,
          'anchor_text_for_next' => null,
        ],
        'invalid_caches' => [
          'block_html' => null,
          'layout' => null,
          'translate' => null,
          'full_page' => null,
        ],
        'head' => [
          'default_title' => 'Rotary Europe Power Equipment',
          'default_media_type' => 'text/html',
          'default_charset' => 'utf-8',
          'demonotice' => '1',
          'title_prefix' => null,
          'title_suffix' => null,
          'default_description' => null,
          'default_keywords' => null,
          'includes' => null,
        ],
        'search_engine_robots' => [
          'default_robots' => 'NOINDEX,NOFOLLOW',
          'default_custom_instructions' => '
User-agent: *
Disallow: /index.php/
Disallow: /*?
Disallow: /checkout/
Disallow: /app/
Disallow: /lib/
Disallow: /*.php$
Disallow: /pkginfo/
Disallow: /report/
Disallow: /var/
Disallow: /catalog/
Disallow: /customer/
Disallow: /sendfriend/
Disallow: /review/
Disallow: /*SID=
',
          'custom_instructions' => null,
        ],
        'header' => [
          'welcome' => 'Welcome at the Rotary Europe Website',
          'logo_width' => null,
          'logo_height' => null,
          'logo_alt' => null,
          'logo_src' => 'default/logo-rotary-red.png',
        ],
        'footer' => [
          'copyright' => 'Copyright © 2013-present Magento, Inc. All rights reserved.',
          'report_bugs' => '1',
          'absolute_footer' => null,
        ],
        'watermark' => [
          'image_position' => 'stretch',
          'small_image_position' => 'stretch',
          'thumbnail_position' => 'stretch',
          'image_size' => null,
          'image_imageOpacity' => null,
          'small_image_size' => null,
          'small_image_imageOpacity' => null,
          'thumbnail_size' => null,
          'thumbnail_imageOpacity' => null,
          'swatch_image_size' => null,
          'swatch_image_imageOpacity' => null,
          'swatch_image_position' => 'stretch',
        ],
        'email' => [
          'header_template' => 'design_email_header_template',
          'footer_template' => 'design_email_footer_template',
          'logo_alt' => null,
          'logo_width' => null,
          'logo_height' => null,
        ],
        'theme' => [
          'theme_id' => 'frontend/Alothemes/market4',
        ],
      ],
    ],
  ],
  'scopes' => [
    'websites' => [
      'admin' => [
        'website_id' => '0',
        'code' => 'admin',
        'name' => 'Admin',
        'sort_order' => '0',
        'default_group_id' => '0',
        'is_default' => '0',
      ],
      'base' => [
        'website_id' => '1',
        'code' => 'base',
        'name' => 'Main Website',
        'sort_order' => '0',
        'default_group_id' => '1',
        'is_default' => '1',
      ],
    ],
    'groups' => [
      0 => [
        'group_id' => '0',
        'website_id' => '0',
        'name' => 'Default',
        'root_category_id' => '0',
        'default_store_id' => '0',
        'code' => 'default',
      ],
      1 => [
        'group_id' => '1',
        'website_id' => '1',
        'name' => 'Main Website Store',
        'root_category_id' => '2',
        'default_store_id' => '1',
        'code' => 'main_website_store',
      ],
    ],
    'stores' => [
      'admin' => [
        'store_id' => '0',
        'code' => 'admin',
        'website_id' => '0',
        'group_id' => '0',
        'name' => 'Admin',
        'sort_order' => '0',
        'is_active' => '1',
      ],
      'default' => [
        'store_id' => '1',
        'code' => 'default',
        'website_id' => '1',
        'group_id' => '1',
        'name' => 'Default Store View',
        'sort_order' => '0',
        'is_active' => '1',
      ],
    ],
  ],
  'themes' => [
    'frontend/Magento/blank' => [
      'parent_id' => null,
      'theme_path' => 'Magento/blank',
      'theme_title' => 'Magento Blank',
      'is_featured' => '0',
      'area' => 'frontend',
      'type' => '0',
      'code' => 'Magento/blank',
    ],
    'frontend/Magento/luma' => [
      'parent_id' => 'Magento/blank',
      'theme_path' => 'Magento/luma',
      'theme_title' => 'Magento Luma',
      'is_featured' => '0',
      'area' => 'frontend',
      'type' => '0',
      'code' => 'Magento/luma',
    ],
    'adminhtml/Magento/backend' => [
      'parent_id' => null,
      'theme_path' => 'Magento/backend',
      'theme_title' => 'Magento 2 backend',
      'is_featured' => '0',
      'area' => 'adminhtml',
      'type' => '0',
      'code' => 'Magento/backend',
    ],
  ],
  'i18n' => [
  ],
];
