name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  basic-test:
    name: Basic Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test scripts
        run: make basic-tests

  magento-packaging:
    name: Magento Packaging
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test packaging of real magento source
        run: make magento2-test
